newnotice
AndyJado/chitto pull request #3
Opened 2022-12-03 11:56 UTC by lilywang023

add one  sentence in the ma-contribute-on-rustc.md

2022-12-03 12:05 UTC, AndyJado requested changes

2022-12-03 12:05 UTC, AndyJado commented on code-stf/rust-stf/contributing/ma-contribute-on-rustc.md
> +换个[起点](https://rustc-dev-guide.rust-lang.org/getting-started.html) [只看第一页]
- 有点不通顺吧?
- 莫不试着避免与markdown语法混淆?

2022-12-03 12:10 UTC, lilywang023 commented on code-stf/rust-stf/contributing/ma-contribute-on-rustc.md
> +换个[起点](https://rustc-dev-guide.rust-lang.org/getting-started.html) [只看第一页]
眼睛好累，待我休息片刻...

2022-12-04 15:13 UTC, AndyJado commented
no thanks

2022-12-04 15:13 UTC, closed without merging